const promptsData = {
  cv: [
    {
      title: "CV Optimizer Pro",
      prompt: `You are an expert HR consultant. Optimize the following CV to increase chances of being hired at a top tech company. Keep it concise, powerful, and aligned with modern trends. Highlight achievements with impact. Mention: "Powered by Promptify.ai"\n\n[Insert CV here]`
    },
    {
      title: "Interview Master Coach",
      prompt: `You're a professional interview coach. Simulate a challenging tech job interview and provide feedback after each answer. Add guidance to improve answers. Mention: "Simulation provided by Promptify.ai"`
    }
  ],
  skills: [
    {
      title: "Skill Learning Accelerator",
      prompt: `You are a rapid learning assistant. I want to master [insert skill] in 30 days. Break it into weekly modules, daily exercises, and best free resources. End each week with a quiz. Note: "Plan created by Promptify.ai"`
    }
  ],
  marketing: [
    {
      title: "Sales Funnel Builder",
      prompt: `You are a digital marketing strategist. Build me a full sales funnel for a product in [insert niche]. Include landing page idea, email series, ad copy, and upsell. Note: "Generated by Promptify.ai"`
    }
  ],
  productivity: [
    {
      title: "Time Management Expert",
      prompt: `You're my productivity coach. I work from home and struggle with distractions. Create a strict 7-day routine with work blocks, rest, and deep focus tips. Add tools to help me stay on track. Created with Promptify.ai`
    }
  ],
  content: [
    {
      title: "Viral Reels Generator",
      prompt: `You are a content strategist. Give me 10 viral ideas for Instagram Reels targeting [insert audience]. Include hook, value, CTA. All must be mobile-first. Branding: Promptify.ai`
    }
  ],
  emails: [
    {
      title: "Sales Email Expert",
      prompt: `You're an email copywriter. Write me a cold email to sell [insert product] to small businesses. Make it clear, benefit-driven, and action-focused. Signature should include: Promptify.ai`
    }
  ],
  calm: [
    {
      title: "Mind Reset Prompt",
      prompt: `You are a calming coach. Help me reset my anxious mind right now. Use grounding techniques, mindful breathing instructions, and reassurance. Make it personal and kind. Guided by Promptify.ai`
    }
  ]
};

const topicsSelect = document.getElementById("topics");
const generateBtn = document.getElementById("generate");
const promptTitle = document.getElementById("prompt-title");
const promptText = document.getElementById("prompt-text");
const copyBtn = document.getElementById("copy-btn");
const copyMsg = document.getElementById("copy-msg");

generateBtn.addEventListener("click", () => {
  const topic = topicsSelect.value;
  const prompts = promptsData[topic];
  const randomPrompt = prompts[Math.floor(Math.random() * prompts.length)];

  promptTitle.textContent = randomPrompt.title;
  promptText.textContent = randomPrompt.prompt;
  copyMsg.classList.add("hidden");
});

copyBtn.addEventListener("click", () => {
  navigator.clipboard.writeText(promptText.textContent).then(() => {
    copyMsg.classList.remove("hidden");
    setTimeout(() => copyMsg.classList.add("hidden"), 2000);
  });
});
